name: abstract_calendar
description: A new Flutter package.
version: 1.0.0
author: Ali Ghanbari

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  abstarct_date: ^1.0.1

  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
